'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { AuthLayout } from '../../components/auth/AuthLayout';

export default function TwoFactorPage() {
  const [code, setCode] = useState(['', '', '', '', '', '']);
  const [isLoading, setIsLoading] = useState(false);
  const [useBackupCode, setUseBackupCode] = useState(false);

  const handleInput = (index: number, value: string) => {
    if (value.length > 1) value = value[value.length - 1];
    const newCode = [...code];
    newCode[index] = value;
    setCode(newCode);

    // Auto-focus next field
    if (value && index < 5) {
      const nextInput = document.getElementById(`otp-${index + 1}`);
      nextInput?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      const prevInput = document.getElementById(`otp-${index - 1}`);
      prevInput?.focus();
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setTimeout(() => {
      setIsLoading(false);
      window.location.href = '/dashboard';
    }, 1200);
  };

  return (
    <AuthLayout
      headline="Two-Factor Security Verification."
      subheadline="Protecting your executive telemetry with mandatory multi-factor authentication."
      topRightText="Having trouble?"
      topRightLinkText="Use Backup Code"
      topRightLinkHref="#"
      badgeText="2FA SECURITY"
    >
      <div className="space-y-6">
        <div className="w-14 h-14 rounded-2xl bg-primary/10 text-primary flex items-center justify-center">
          <svg width="28" height="28" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0110 0v4"/></svg>
        </div>

        <div className="space-y-2">
          <h2 className="text-[32px] sm:text-[36px] font-extrabold tracking-tight text-gray-950 font-sans">
            Enter 2FA Code
          </h2>
          <p className="text-[15px] text-gray-600">
            Enter the 6-digit authentication code generated by your authenticator app.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {!useBackupCode ? (
            <div className="flex items-center justify-between gap-2">
              {code.map((digit, idx) => (
                <input
                  key={idx}
                  id={`otp-${idx}`}
                  type="text"
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={1}
                  value={digit}
                  onChange={(e) => handleInput(idx, e.target.value)}
                  onKeyDown={(e) => handleKeyDown(idx, e)}
                  autoComplete="one-time-code"
                  className="w-12 h-14 bg-white border border-gray-300 focus:border-primary focus:ring-2 focus:ring-primary/20 rounded-[10px] text-center text-[22px] font-bold font-mono text-gray-900 outline-none transition-all shadow-sm"
                />
              ))}
            </div>
          ) : (
            <div className="space-y-1.5">
              <label htmlFor="backup" className="text-[14px] font-bold text-gray-900 block">
                Emergency Backup Code
              </label>
              <input
                id="backup"
                type="text"
                placeholder="XXXX-XXXX-XXXX"
                className="w-full h-12 bg-white border border-gray-300 focus:border-primary focus:ring-2 focus:ring-primary/20 rounded-[10px] px-4 font-mono text-[15px] text-gray-900 outline-none"
              />
            </div>
          )}

          <button
            type="submit"
            disabled={isLoading || (!useBackupCode && code.join('').length < 6)}
            className="w-full h-12 bg-primary hover:bg-primary/90 disabled:opacity-50 text-white font-bold text-[15px] rounded-[10px] shadow-sm hover:shadow transition-all flex items-center justify-center space-x-2"
          >
            {isLoading ? (
              <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : (
              <>
                <span>Verify & Continue</span>
                <svg width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
              </>
            )}
          </button>
        </form>

        <div className="flex items-center justify-between text-[13px] pt-2 border-t border-gray-200">
          <button
            type="button"
            onClick={() => setUseBackupCode(!useBackupCode)}
            className="font-bold text-primary hover:underline"
          >
            {useBackupCode ? 'Use 6-Digit Authenticator App' : 'Use Backup Code'}
          </button>
          <Link href="/login" className="text-gray-600 hover:text-gray-900 font-semibold">
            Cancel
          </Link>
        </div>
      </div>
    </AuthLayout>
  );
}
