"""add_reset_token_fields

Revision ID: e23d1b45a8c7
Revises: 9a124956e398
Create Date: 2026-08-07 14:21:10.309248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23d1b45a8c7'
down_revision: Union[str, Sequence[str], None] = '9a124956e398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_expires_at')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
